### ISSUE TITLE
Heroku says heroku-remote will break in less than a month :(

### ISSUE THREAD

**Issue by indirect** [tpope/heroku-remote#2]
```
$ heroku push --app APPNAME
 ▸    push is not a heroku command.
 ▸    Perhaps you meant ps?
 ▸    Run heroku _ to run heroku ps --app APPNAME.
 ▸    Run heroku help for a list of available commands.
WARNING: https://github.com/tpope/heroku-remote is a deprecated Ruby plugin
WARNING: Check to see if there is a version of this plugin using the new Node.js Heroku CLI
git push https://git.heroku.com/APPNAME.git HEAD:master
Everything up-to-date
 !    The Heroku Legacy Platform API will be Sunset on April 15th 2017. Please
update your client access or the Heroku CLI to the latest version. See 
https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2 for more details.
```

**Comment by tpope** [comment]
No problem, all I have to do is completely re-implement this and 5 other plugins in JavaScript.

**Comment by tpope** [comment]
More constructively, it's a simple plugin, and I can't imagine it would be that hard to port per se, but I haven't so much as taken a look at what a Node plugin looks like.

**Comment by tpope** [comment]
So I just updated my heroku-toolbelt, and I'm getting the Ruby warning, but not the API warning. Maybe you've got some other plugin installed causing that?

**Comment by tpope** [comment]
Okay, the short of it is that it's easy enough to update to the new platform API, but the `platform-api` gem isn't included with the legacy Ruby plugin interface, so you'll have to install it yourself. I've added a bunch of `if` statements to use it if it's available.

On the subject of moving to a Node CLI implementation, I didn't look super hard, but I can't even find an example plugin to use as a starting point. Even https://devcenter.heroku.com/articles/using-cli-plugins uses as an example a pure Ruby plugin.

**Comment by indirect** [comment]
Wow, you're fast! Thanks for the investigation, and I guess I'll go complain in some support tickets about the shitty deprecation massage now.

**Comment by tpope** [comment]
P.S. https://github.com/tpope/heroku-fucking-console/commit/a60e2c9dd78cffcc597061d6564366edfb5d1a68

**Comment by indirect** [comment]
@tpope 🎉🎉🎉🎉🎉🎉🎉
